### ISSUE TITLE
Your awesome presentation 🥇 

### ISSUE THREAD

**Issue by th-zf** [BCX22-Group1/serial-throttle#1]
[Posted on all of your repos ;)]

Hi Team 1,
thanks your participation, engagement and spirit for the hackathon. I hope you had great time hacking 💯 . As a coach, I can tell you all did a great job. On your developed solutions, presentations and the pitches.

Here is my request: Can you please share the latest version of your presentation?

You can upload it to your repository.
Or share it with me ([thomas.hochstrasser@zf.com](mailto:thomas.hochstrasser@zf.com)). I will make them available on an another repository in the 'https://github.com/Eclipse-SDV-Hackathon-BCX' repository.
If multiple files are required. Please zip them together 👍 .

Best regards,
Thomas Hochstrasser

**Comment by mariuskreutzer** [comment]
Tracked here: https://github.com/Eclipse-SDV-Hackathon-BCX/Group1-TruckCarla-eCAL/issues/1
